{{- if not .Values.global.init.admin.password.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-admin
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- tpl ( .Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if or .annotation $.Values.commonAnnotations $.Values.global.commonAnnotations }}
    {{ $annotations := merge (dict) .annotation $.Values.commonAnnotations $.Values.global.commonAnnotations }}
  annotations:
    {{- tpl ( $annotations | toYaml ) $ | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-password: {{ include "common.password" (dict "Namespace" .Release.Namespace "SecretName" ( printf "%s-admin" ( include "common.fullname" . ) ) "PasswordKey" "admin-password") }}
{{- end }}
