{{- $extraDeploy := list }}
{{- $extraDeploy = concat $extraDeploy .Values.extraDeploy }}
{{- $extraDeploy = concat $extraDeploy .Values.global.extraDeploy }}
{{- range $extraDeploy }}
---
{{ . | toYaml }}
{{- end }}
