{{- if and .Values.global.metrics.enabled .Values.global.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ default (include "common.namespace" .) .Values.global.metrics.podMonitor.namespace }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubernetes-event-exporter
    {{- if .Values.global.metrics.podMonitor.labels }}
    {{- tpl ( .Values.global.metrics.podMonitor.labels | toYaml ) $ | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonLabels }}
    {{- tpl ( .Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- tpl (  .Values.global.commonAnnotations | toYaml ) $ | nindent 4 }}
  {{- end }}
spec:
  attachMetadata:
    node: true
  {{- if .Values.global.metrics.podMonitor.jobLabel }}
  jobLabel: {{ .Values.global.metrics.podMonitor.jobLabel }}
  {{- end }}
  podMetricsEndpoints:
    {{- $defaultEndpoint := pick .Values.global.metrics.podMonitor "port" "interval" "scrapeTimeout" "relabelings" "metricRelabelings" "honorLabels" }}
    {{- $endpoints := ternary (.Values.global.metrics.podMonitor.podMetricsEndpoints) (list (dict "path" .Values.global.metrics.podMonitor.path)) (empty .Values.global.metrics.podMonitor.path) }}
    {{- range $endpoints }}
    {{- $endpoint := merge . $defaultEndpoint }}
    - port: {{ $endpoint.port }}
      path: {{ $endpoint.path }}
      {{- if $endpoint.interval }}
      interval: {{ $endpoint.interval }}
      {{- end }}
      {{- if $endpoint.scrapeTimeout }}
      scrapeTimeout: {{ $endpoint.scrapeTimeout }}
      {{- end }}
      {{- if $endpoint.relabelings }}
      relabelings: {{- tpl ( $endpoint.relabelings | toYaml ) $ | nindent 6 }}
      {{- end }}
      {{- if $endpoint.metricRelabelings }}
      metricRelabelings: {{- tpl ( $endpoint.metricRelabelings | toYaml ) $ | nindent 6 }}
      {{- end }}
      {{- if $endpoint.honorLabels }}
      honorLabels: {{ $endpoint.honorLabels }}
      {{- end }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "common.namespace" . | quote }}
  selector:
    matchLabels: {{- include "common.matchLabels" . | nindent 6 }}
      {{- if .Values.global.metrics.podMonitor.selector }}
      {{- tpl ( .Values.global.metrics.podMonitor.selector | toYaml ) $ | nindent 6 }}
      {{- end }}
{{- end }}
