{{- $root := . -}}
{{- $secretMaps := merge (dict) .Values.secretMaps .Values.global.secretMaps }}
{{- range $name, $secret := $secretMaps -}}
{{- if $secret.enabled }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if eq $name "default" }}{{ include "common.fullname" $ }}{{ else }}{{ $name }}{{ end }}
  namespace: {{ include "common.namespace" $root | quote }}
  labels: {{- include "common.labels" $root | nindent 4 }}
    {{- if $root.Values.global.commonLabels }}
    {{- tpl ( $root.Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if or .annotation $.Values.commonAnnotations $.Values.global.commonAnnotations }}
    {{ $annotations := merge (dict) .annotation $.Values.commonAnnotations $.Values.global.commonAnnotations }}
  annotations:
    {{- tpl ( $annotations | toYaml ) $ | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := $secret.values }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}

{{- end }}
{{- end -}}
