global:
  mail:
    smtp:
      host: <change me>
      port: <change me>
      tls: true
    fromPersonal: <change me>
    fromEmail: <change me>
    confirmUrl: <change me>
  cookie_domain: <change me>
  selfRegistrationEnabled: false
  throttle_login_delay: 5s
  auth:
    tokens:
      accessSecretExpiration: 2m
      refreshSecretExpiration: 30d
  init:
    admin:
      email: <change me>
      password:
        secret:
          name: ""
      firstname: <change me>
      lastname: <change me>
      roles: {}
      readonly: true
    organization:
      id: <change me>
      name: <change me>
      description: <change me>
      readonly: true
  mongo: "mongodb://mongo:27017/account"
  jvm:
    options: |
      -Xmx128M
      -Xss228k
      -XX:+UseG1GC
      -XX:+UseGCOverheadLimit
      -XX:GCTimeLimit=90
      -XX:-OmitStackTraceInFastThrow
      -Dorg.quartz.scheduler.skipUpdateCheck=true
      -Dsun.jnu.encoding=UTF-8
      -Dfile.encoding=UTF-8
  logs:
    loglevel: DEBUG
    configuration: |
      <configuration scan="true">
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n</pattern>
            </encoder>
        </appender>
      
        <logger name="org" level="ERROR"/>
        <logger name="oap.http.Server" level="${OAP_HTTP_SERVER_LOGGING_LEVEL:-WARN}"/>
        <logger name="io.undertow" level="WARN"/>
        <logger name="oap.application.remote" level="WARN"/>
        <logger name="javax.management" level="ERROR" />
      
        <root level="${APP_LOGGING_LEVEL:-DEBUG}">
            <appender-ref ref="STDOUT"/>
        </root>
      </configuration>

  statefulset:
    enabled: true
    replicaCount: 1
  nameOverride: account
  fullnameOverride: ""
  commonAnnotations: {}
  commonLabels: {}

  #  podSecurityContext:
  #    enabled: true
  #    fsGroup: 1001
  #  containerSecurityContext:
  #    enabled: true
  #    runAsUser: 1001
  #    runAsNonRoot: true

  imageRegistry: ""
  imagePullSecrets: []
  extraDeploy: []

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      port: httpprivate
  image:
    registry: docker.xenoss.io
    repository: "xenoss-account"
    tag: "XXX"
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    ##   - myRegistryKeySecretName
    loglevel: DEBUG

  service:
    enabled: true
    clusterIP: None
    ports:
      http: 8080
      httpprivate: 8081
    ## Node ports to expose
    nodePorts:
      http: ""
      httpprivate: ""
    extraPorts:
      - name: http
        port: 8080
        targetPort: http
      - name: httpprivate
        port: 8081
        targetPort: httpprivate

common:
  containerPorts:
    - name: http
      containerPort: 8080
    - name: httpprivate
      containerPort: 8081

  envVars:
    - name: MAIL_HOST
      value: "{{ .Values.global.mail.smtp.host }}"
    - name: MAIL_PORT
      value: "{{ .Values.global.mail.smtp.port }}"
    - name: MAIL_TLS
      value: "{{ .Values.global.mail.smtp.tls }}"
    - name: MAIL_FROM_PERSONAL
      value: "{{ .Values.global.mail.fromPersonal }}"
    - name: MAIL_FROM_EMAIL
      value: "{{ .Values.global.mail.fromEmail }}"
    - name: ACCOUNT_CONFIRM_URL
      value: "{{ .Values.global.mail.confirmUrl }}"

    - name: COOKIE_DOMAIN
      value: "{{ .Values.global.cookie_domain }}"
    - name: APP_LOGGING_LEVEL
      value: "{{ .Values.global.logs.loglevel }}"
    - name: MONGO_CONNECTION_URL
      value: "{{ .Values.global.mongo }}"

    - name: DEFAULT_SYSTEM_ADMIN_EMAIL
      value: "{{ .Values.global.init.admin.email }}"
    - name: DEFAULT_SYSTEM_ADMIN_EMAIL
      value: "{{ .Values.global.init.admin.email }}"
    - name: DEFAULT_SYSTEM_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "{{ .Values.global.init.admin.password.secret.name | default ( printf \"%s-admin\" ( include \"common.fullname\" . ) ) }}"
          key: admin-password
    - name: DEFAULT_SYSTEM_ADMIN_FIRST_NAME
      value: "{{ .Values.global.init.admin.firstname }}"
    - name: DEFAULT_SYSTEM_ADMIN_LAST_NAME
      value: "{{ .Values.global.init.admin.lastname }}"
    - name: DEFAULT_SYSTEM_ADMIN_ROLES
      value: "json({{ .Values.global.init.admin.roles | toJson }})"
    - name: DEFAULT_SYSTEM_ADMIN_READ_ONLY
      value: "{{ .Values.global.init.admin.readonly | toString }}"

    - name: DEFAULT_ORGANIZATION_ID
      value: "{{ .Values.global.init.organization.id }}"
    - name: DEFAULT_ORGANIZATION_NAME
      value: "{{ .Values.global.init.organization.name }}"
    - name: DEFAULT_ORGANIZATION_DESCRIPTION
      value: "{{ .Values.global.init.organization.description }}"
    - name: DEFAULT_ORGANIZATION_READ_ONLY
      value: "{{ .Values.global.init.organization.readonly | toString }}"

    - name: SELF_REGISTRATION_ENABLED
      value: "{{ .Values.global.selfRegistrationEnabled | toString }}"
    - name: THROTTLE_LOGIN_DELAY
      value: "{{ .Values.global.throttle_login_delay }}"

    - name: ACCESS_SECRET_EXPIRATION
      value: "{{ .Values.global.auth.tokens.accessSecretExpiration }}"
    - name: REFRESH_SECRET_EXPIRATION
      value: "{{ .Values.global.auth.tokens.refreshSecretExpiration }}"
  configMaps:
    default:
      enabled: true
      files:
        vm.options: "{{ .Values.global.jvm.options }}"
        logback.xml: "{{ .Values.global.logs.configuration }}"

  volumes:
    - name: "{{ include \"common.fullname\" $ }}"
      configMap:
        name: "{{ include \"common.fullname\" $ }}"
  volumeMounts:
    - name: "{{ include \"common.fullname\" $ }}"
      mountPath: "/opt/xenoss-account/conf/vm.options"
      subPath: vm.options
      readOnly: true
    - name: "{{ include \"common.fullname\" $ }}"
      mountPath: /opt/xenoss-account/conf/logback.xml
      subPath: logback.xml
      readOnly: true

  podAnnotations:
    reloader.stakater.com/auto: "true"
