{{- if .Values.global.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- tpl ( .Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if or .Values.pod.annotations .Values.global.pod.annotations .Values.commonAnnotations .Values.global.commonAnnotations }}
    {{ $annotations := merge (dict) .Values.pod.annotations .Values.global.pod.annotations .Values.commonAnnotations .Values.global.commonAnnotations }}
  annotations:
    {{- tpl ( $annotations | toYaml ) $ | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.updateStrategy }}
  updateStrategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels" . | nindent 8 }}
        {{- if .Values.global.podLabels }}
        {{- tpl ( .Values.global.podLabels | toYaml ) $ | nindent 8 }}
        {{- end }}
      {{- include "common.podAnnotations" . }}
    spec:
      {{- include "common.pullSecrets" $ | nindent 6 }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector: {{- tpl ( .Values.global.nodeSelector | toYaml ) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.global.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.global.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "common.name" . }}
          image: {{ include "common.image" $ }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | quote }}
          {{- if .Values.global.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.global.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.global.command }}
          command: {{- tpl ( .Values.global.command | toYaml ) $ | nindent 12 }}
          {{- end }}
          {{- if .Values.global.args }}
          args: {{- tpl ( .Values.global.args | toYaml ) $ | nindent 12 }}
          {{- end }}
          {{- if or .Values.global.extraEnvVars .Values.envVars }}
            {{- $envVars := concat (list) .Values.envVars .Values.global.extraEnvVars }}
          env:
            {{- tpl ( $envVars | toYaml ) $ | nindent 12 }}
          {{- end }}
{{- include "pod.content" $ }}
{{- end }}
