{{- if .Values.global.deployment.enabled }}
{{ $extraVolumes := list }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- tpl ( .Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if or .Values.pod.annotations .Values.global.pod.annotations .Values.commonAnnotations .Values.global.commonAnnotations }}
    {{ $annotations := merge (dict) .Values.pod.annotations .Values.global.pod.annotations .Values.commonAnnotations .Values.global.commonAnnotations }}
  annotations:
    {{- tpl ( $annotations | toYaml ) $ | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.global.deployment.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels" . | nindent 8 }}
        {{- if .Values.global.podLabels }}
        {{- tpl ( .Values.global.podLabels | toYaml ) $ | nindent 8 }}
        {{- end }}
      {{- include "common.podAnnotations" . }}
    spec:
      hostname: {{ template "common.fullname" . }}
{{- include "pod.content" $ }}
{{- end }}
