{{- if .Values.global.ingress.enabled }}
{{- if .Values.global.ingress.secrets }}
{{- range .Values.global.ingress.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels" $ | nindent 4 }}
    {{- if $.Values.global.commonLabels }}
    {{- tpl ( .Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if $.Values.global.commonAnnotations }}
  annotations: {{- tpl ( .Values.global.commonAnnotations | toYaml ) $ | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
{{- if and .Values.global.ingress.tls .Values.global.ingress.selfSigned }}
{{- $secretName := printf "%s-tls" .Values.global.ingress.hostname }}
{{- $ca := genCA "account-ca" 365 }}
{{- $cert := genSignedCert .Values.global.ingress.hostname nil (list .Values.global.ingress.hostname) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- tpl ( .Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- tpl ( .Values.global.commonAnnotations | toYaml ) $ | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "tls.crt" "defaultValue" $cert.Cert "context" $) }}
  tls.key: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "tls.key" "defaultValue" $cert.Key "context" $) }}
  ca.crt: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "ca.crt" "defaultValue" $ca.Cert "context" $) }}
{{- end }}
{{- end }}
