{{- if and .Values.global.persistence.enabled ( ne ( eq .Values.global.persistence.localpath "" ) ) }}
{{- range until (include "commmon.replicaCount" . | int ) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-{{ template "common.fullname" $ }}-{{ . }}
  namespace: {{ include "common.namespace" $ | quote }}
  {{- if $.Values.global.persistence.annotations }}
  annotations:
    {{- tpl ( $.Values.global.persistence.annotations | toYaml ) $ | nindent 4 }}
  {{- end }}
spec:
  capacity:
    storage: {{ $.Values.global.persistence.size }}
  accessModes:
  {{- range $.Values.global.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  storageClassName: {{ template "common.fullname" $ }}-storage
  local:
    path: {{ $.Values.global.persistence.localpath }}
  {{- if $.Values.global.nodeSelector }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
    {{- range $key, $value := $.Values.global.nodeSelector }}
            - key: {{ tpl $key $  | quote }}
              operator: In
              values:
                - {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
