{{- if and .Values.global.metrics.enabled .Values.global.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ default (include "common.namespace" .) .Values.global.metrics.serviceMonitor.namespace }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubernetes-event-exporter
    {{- if .Values.global.metrics.serviceMonitor.labels }}
    {{- tpl ( .Values.global.metrics.serviceMonitor.labels | toYaml ) $ | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonLabels }}
    {{- tpl ( .Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- tpl (  .Values.global.commonAnnotations | toYaml ) $ | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.global.metrics.serviceMonitor.jobLabel }}
  {{- end }}
  endpoints:
    {{- $defaultEndpoint := pick .Values.global.metrics.serviceMonitor "port" "interval" "scrapeTimeout" "relabelings" "metricRelabelings" "honorLabels" }}
    {{- $endpoints := ternary (.Values.global.metrics.serviceMonitor.endpoints) (list (dict "path" .Values.global.metrics.serviceMonitor.path)) (empty .Values.global.metrics.serviceMonitor.path) }}
    {{- range $endpoints }}
    {{- $endpoint := merge . $defaultEndpoint }}
    - port: {{ $endpoint.port }}
      path: {{ $endpoint.path }}
      {{- if $endpoint.interval }}
      interval: {{ $endpoint.interval }}
      {{- end }}
      {{- if $endpoint.scrapeTimeout }}
      scrapeTimeout: {{ $endpoint.scrapeTimeout }}
      {{- end }}
      {{- if $endpoint.relabelings }}
      relabelings: {{- tpl ( $endpoint.relabelings | toYaml ) $ | nindent 6 }}
      {{- end }}
      {{- if $endpoint.metricRelabelings }}
      metricRelabelings: {{- tpl ( $endpoint.metricRelabelings | toYaml ) $ | nindent 6 }}
      {{- end }}
      {{- if $endpoint.honorLabels }}
      honorLabels: {{ $endpoint.honorLabels }}
      {{- end }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "common.namespace" . | quote }}
  selector:
    matchLabels: {{- include "common.matchLabels" . | nindent 6 }}
      {{- if .Values.global.metrics.serviceMonitor.selector }}
      {{- tpl ( .Values.global.metrics.serviceMonitor.selector | toYaml ) $ | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: metrics
{{- end }}
