{{- if .Values.global.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- tpl ( .Values.global.commonLabels | toYaml ) $ | nindent 4 }}
    {{- end }}
  {{- if or .Values.pod.annotations .Values.global.pod.annotations .Values.commonAnnotations .Values.global.commonAnnotations }}
    {{ $annotations := merge (dict) .Values.pod.annotations .Values.global.pod.annotations .Values.commonAnnotations .Values.global.commonAnnotations }}
  annotations:
    {{- tpl ( $annotations | toYaml ) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.global.statefulset.replicaCount }}
  podManagementPolicy: {{ .Values.global.podManagementPolicy | quote }}
  selector:
    matchLabels: {{- include "common.matchLabels" . | nindent 6 }}
  serviceName: {{ printf "%s-headless" (include "common.fullname" .) }}
  {{- if .Values.global.updateStrategy }}
  updateStrategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels" . | nindent 8 }}
        {{- if .Values.global.podLabels }}
        {{- tpl ( .Values.global.podLabels | toYaml ) $ | nindent 8 }}
        {{- end }}
      {{- include "common.podAnnotations" . }}
    spec:
      hostname: {{ template "common.fullname" . }}
      {{- if .Values.global.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.global.terminationGracePeriodSeconds }}
      {{- end }}
{{- include "pod.content" $ }}
{{- end }}
