global:
  profiles:
    bs:
      cron: ""
  clickhouse:
    database: test
    host: clickhouse
  jvm:
    options: |
      -Xmx1G
      -Xss228k
      -XX:+UseG1GC
      -XX:+UseGCOverheadLimit
      -XX:GCTimeLimit=90
      -XX:-OmitStackTraceInFastThrow
      -Dorg.quartz.scheduler.skipUpdateCheck=true
      -Dsun.jnu.encoding=UTF-8
      -Dfile.encoding=UTF-8
  logs:
    loglevel: DEBUG
    configuration: |
      <configuration scan="true">
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n</pattern>
            </encoder>
        </appender>
      
        <logger name="org" level="ERROR"/>
        <logger name="oap.http.Server" level="${OAP_HTTP_SERVER_LOGGING_LEVEL:-WARN}"/>
        <logger name="io.undertow" level="WARN"/>
        <logger name="oap.application.remote" level="WARN"/>
        <logger name="javax.management" level="ERROR" />
      
        <root level="${APP_LOGGING_LEVEL:-DEBUG}">
            <appender-ref ref="STDOUT"/>
        </root>
      </configuration>



  deployment:
    enabled: true
    replicaCount: 1
  nameOverride: dmp
  fullnameOverride: ""
  commonAnnotations: {}
  commonLabels: {}

  imageRegistry: ""
  imagePullSecrets: []
  extraDeploy: []

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
    podMonitor:
      enabled: true
      port: httpprivate

  image:
    registry: docker.xenoss.io
    repository: "xenoss-dmp"
    tag: "XXX"
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    ##   - myRegistryKeySecretName
    loglevel: DEBUG

  service:
    enabled: true
    ports:
      http: 8080
      httpprivate: 8081
    ## Node ports to expose
    nodePorts:
      http: ""
      httpprivate: ""
    extraPorts:
      - name: httpprivate
        port: 8081
        targetPort: httpprivate


common:
  containerPorts:
    - name: http
      containerPort: 8080
    - name: httpprivate
      containerPort: 8081
  envVars: |
    - name: APP_LOGGING_LEVEL
      value: "{{ .Values.global.logs.loglevel }}"

    - name: CLICKHOUSE_HOST
      value: "{{ .Values.global.clickhouse.host }}"
    - name: CLICKHOUSE_DATABASE
      value: "{{ .Values.global.clickhouse.database }}"

    {{- if .Values.global.profiles.bs.cron }}
    - name: BID_SHADING_CRON
      value: "{{ .Values.global.profiles.bs.cron }}"
    {{- end }}
  configMaps:
    default:
      enabled: true
      files:
        vm.options: "{{ .Values.global.jvm.options }}"
        logback.xml: "{{ .Values.global.logs.configuration }}"
  volumes:
    - name: "{{ include \"common.fullname\" $ }}"
      configMap:
        name: "{{ include \"common.fullname\" $ }}"
  volumeMounts:
    - name: "{{ include \"common.fullname\" $ }}"
      mountPath: /opt/xenoss-dmp/conf/vm.options
      subPath: vm.options
      readOnly: true
    - name: "{{ include \"common.fullname\" $ }}"
      mountPath: /opt/xenoss-filex/conf/logback.xml
      subPath: logback.xml
      readOnly: true
