annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.0.7
dependencies:
  - name: common
    repository: https://nexus.xenoss.io/repository/xenoss-helm-oss
    version: 2.0.6
home: https://xenoss.com
name: account
sources:
  - https://github.com/xenoss/xenoss.account
version: 1.0.7
