annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    repository: https://nexus.xenoss.io/repository/xenoss-helm-oss
    version: 2.0.3
home: https://xenoss.com
name: dmp
sources:
  - https://github.com/xenoss/xenoss-dmp
version: 1.0.0
