annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.0.3
dependencies:
  - name: common
    repository: https://nexus.xenoss.io/repository/xenoss-helm-oss
    version: 2.0.5
home: https://xenoss.com
name: uploader
sources:
  - https://github.com/xenoss/xenoss.reporting
version: 1.0.3
