annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 0.0.1
dependencies:
  - name: common
    repository: https://nexus.xenoss.io/repository/xenoss-helm-oss
    version: 1.x.x
home: https://github.com/adobe/S3Mock
name: s3mock
sources:
  - https://github.com/adobe/S3Mock
version: 0.0.1
