global:
  initialBuckets: []
  #    - test-bucket
  deployment:
    enabled: true
    replicaCount: 1
  nameOverride: s3mock
  fullnameOverride: ""
  commonAnnotations: {}
  commonLabels: {}

  containerPorts:
    - name: http
      containerPort: 9090

  imageRegistry: ""
  imagePullSecrets: []
  extraDeploy: []

  metrics:
    enabled: false
  image:
    registry: docker.io
    repository: "adobe/s3mock"
    tag: "XXX"
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    ##   - myRegistryKeySecretName
    loglevel: DEBUG

  service:
    enabled: true
    ports:
      http: 9090
    ## Node ports to expose
    nodePorts:
      http: ""
    extraPorts:
      - name: http
        port: 8080
        targetPort: http

common:
  envVars:
    - name: initialBuckets
      value: "{{ join \",\" .Values.global.initialBuckets }}"
